name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information to help us understand your request.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New Persona
        - New Skill
        - New MCP Server
        - New Slash Command
        - New Hook
        - Documentation
        - Installation/Setup
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also considered...

  - type: dropdown
    id: persona-related
    attributes:
      label: Related Persona(s)
      description: Which persona(s) would benefit from this feature?
      multiple: true
      options:
        - Engineer
        - QA
        - Product Manager
        - Engineering Manager
        - UX Designer
        - All personas
        - Not persona-specific

  - type: textarea
    id: use-case
    attributes:
      label: Use Case / Examples
      description: Provide specific examples of how this feature would be used
      placeholder: |
        Example 1: When working on...
        Example 2: During code review...

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Perspective)
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Small improvement
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: |
        - Similar features in other tools
        - Mockups or diagrams
        - Related documentation

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I would be willing to submit a PR for this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to help document this feature

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: This feature aligns with the project's goals
          required: true
